<?php
declare (strict_types = 1);

namespace app\admin\model;

use think\Db;
use think\Model;
use think\model\Collection;


class user extends Model
{
    
    //
    public static function getUsers():Collection{
        return self::select();
    }
    public static function create(array $data, array $allowField = [], bool $replace = false): Model
    {
        return parent::create($data, $allowField, $replace); // TODO: Change the autogenerated stub
    }


    public static function searchUser(int $id):Collection{
        $search=user::Where('user_id',$id)->select();
//        user::class;
        return $search;
    }

}
